name: ExplosiveMining
main: src.ExplosiveMining
version: 1.1.3
commands:
   emreload:
      description: Reloads ExplosiveMining config file.
      usage: /emreload
      permission: EM.reload
      permission-message: You don't have permission.
permissions:
    EM.false:
        description: Turns of the explosion chance.
        default: false